version: 0.0
os: linux
files:
  - source: web
    destination: /var/www/mywebsite
    overwrite: true
  - source: backend
    destination: /home/ec2-user/companies-api
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_services.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: root
